//! Generates the UI-facing protocol types into
//! `apps/desktop/src/ipc/generated/` (the only place this crate writes
//! outside itself). `cargo test -p papyrine-ipc --test ts_bindings` rewrites
//! them; with `PAPYRINE_CHECK_TS=1` it fails instead if they are stale.

use papyrine_ipc::*;
use std::fs;
use std::path::{Path, PathBuf};
use ts_rs::{Config, TS};

fn out_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../apps/desktop/src/ipc/generated")
}

fn generate(dir: &Path) {
    let cfg = Config::new().with_out_dir(dir).with_large_int("number");
    macro_rules! all { ($($t:ty),* $(,)?) => { $( <$t as TS>::export_all(&cfg).unwrap(); )* }; }
    all!(
        IpcError,
        ErrorCode,
        Role,
        Hello,
        Progress,
        CommandRequest,
        ChangeSetSummary,
        SectionInfo,
        DocumentInfo,
        PageSizeInfo,
        SearchQuery,
        SearchHit,
        PageTextInfo,
        CharBoxInfo,
        Quad,
        PixelDest,
    );
    // A barrel file so the UI imports from one place.
    let mut names: Vec<String> = fs::read_dir(dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().to_str().map(String::from))
        .filter(|n| n.ends_with(".ts") && n != "index.ts")
        .map(|n| n.trim_end_matches(".ts").to_string())
        .collect();
    names.sort();
    let mut idx =
        String::from("// Generated by papyrine-ipc (tests/ts_bindings.rs). Do not edit.\n");
    for n in &names {
        idx.push_str(&format!("export type {{ {n} }} from \"./{n}\";\n"));
    }
    fs::write(dir.join("index.ts"), idx).unwrap();
}

fn read_all(dir: &Path) -> Vec<(String, String)> {
    let mut v: Vec<_> = fs::read_dir(dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .filter(|e| e.path().extension().is_some_and(|x| x == "ts"))
                .map(|e| {
                    (
                        e.file_name().to_string_lossy().into_owned(),
                        fs::read_to_string(e.path()).unwrap(),
                    )
                })
                .collect()
        })
        .unwrap_or_default();
    v.sort();
    v
}

#[test]
fn generated_types_are_current() {
    let dir = out_dir();
    if std::env::var_os("PAPYRINE_CHECK_TS").is_some() {
        let tmp = std::env::temp_dir().join(format!("papyrine-ts-check-{}", std::process::id()));
        fs::create_dir_all(&tmp).unwrap();
        generate(&tmp);
        let fresh = read_all(&tmp);
        let _ = fs::remove_dir_all(&tmp);
        assert_eq!(
            fresh,
            read_all(&dir),
            "apps/desktop/src/ipc/generated is stale; run cargo test -p papyrine-ipc --test ts_bindings"
        );
        return;
    }
    fs::create_dir_all(&dir).unwrap();
    generate(&dir);
    let idx = fs::read_to_string(dir.join("index.ts")).unwrap();
    assert!(idx.contains("IpcError"));
    let e = fs::read_to_string(dir.join("IpcError.ts")).unwrap();
    assert!(e.contains("code: ErrorCode"), "{e}");
}
