//! Deterministic malformations. Each starts from a small valid base file built by this crate and
//! applies one targeted defect. Where practical the edit preserves length so the rest of the xref
//! stays valid and the defect is isolated; length-changing edits are noted in the description.

use crate::pdf::Out;
use crate::rng::Rng;

pub struct Bases {
    pub classic: Vec<u8>,
    pub flate: Vec<u8>,
    pub objstm: Vec<u8>,
    pub incr: Vec<u8>,
}

fn page_content(n: usize) -> Vec<u8> {
    format!("BT /F1 24 Tf 72 700 Td (Page {n} of the malformation base file) Tj ET\nBT /F1 12 Tf 72 660 Td (Deterministic, generated by Papyrine gen-corpus.) Tj ET\n").into_bytes()
}

const PAGE_FMT: &str =
    "/Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 9 0 R >> >>";

fn trailer_extra() -> String {
    format!("/Info 10 0 R {}", crate::doc::fixed_id(9))
}

fn build_classic(compress: bool) -> Vec<u8> {
    let mut o = Out::new(Vec::new());
    o.header("1.7").unwrap();
    o.obj(1, b"<< /Type /Catalog /Pages 2 0 R >>").unwrap();
    o.obj(2, b"<< /Type /Pages /Kids [3 0 R 4 0 R 5 0 R] /Count 3 >>")
        .unwrap();
    for k in 0..3u32 {
        o.obj(
            3 + k,
            format!("<< {PAGE_FMT} /Contents {} 0 R >>", 6 + k).as_bytes(),
        )
        .unwrap();
    }
    for k in 0..3u32 {
        let c = page_content(k as usize + 1);
        if compress {
            o.flate_stream(6 + k, "", &c, 9).unwrap();
        } else {
            o.stream(6 + k, "", &c).unwrap();
        }
    }
    o.obj(9, b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
        .unwrap();
    o.obj(
        10,
        b"<< /Title (Malformation base) /Producer (Papyrine gen-corpus) >>",
    )
    .unwrap();
    o.finish_classic(1, &trailer_extra()).unwrap();
    o.into_inner()
}

fn build_objstm() -> Vec<u8> {
    let mut o = Out::new(Vec::new());
    o.header("1.7").unwrap();
    for k in 0..3u32 {
        o.flate_stream(6 + k, "", &page_content(k as usize + 1), 9)
            .unwrap();
    }
    o.set_object_stream_numbers(11, 100);
    o.packed(1, b"<< /Type /Catalog /Pages 2 0 R >>".to_vec())
        .unwrap();
    o.packed(
        2,
        b"<< /Type /Pages /Kids [3 0 R 4 0 R 5 0 R] /Count 3 >>".to_vec(),
    )
    .unwrap();
    for k in 0..3u32 {
        o.packed(
            3 + k,
            format!("<< {PAGE_FMT} /Contents {} 0 R >>", 6 + k).into_bytes(),
        )
        .unwrap();
    }
    o.packed(
        9,
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>".to_vec(),
    )
    .unwrap();
    o.packed(10, b"<< /Title (Malformation base) >>".to_vec())
        .unwrap();
    o.finish_xref_stream(12, 1, &trailer_extra()).unwrap();
    o.into_inner()
}

fn build_incremental(base: &[u8]) -> Vec<u8> {
    let prev = last_startxref(base);
    let mut v = base.to_vec();
    let off = v.len();
    let body = b"BT /F1 24 Tf 72 700 Td (Page 3 REVISED by incremental update) Tj ET\n";
    v.extend_from_slice(format!("8 0 obj\n<< /Length {} >>\nstream\n", body.len()).as_bytes());
    v.extend_from_slice(body);
    v.extend_from_slice(b"\nendstream\nendobj\n");
    let xref = v.len();
    v.extend_from_slice(format!("xref\n8 1\n{off:010} 00000 n \ntrailer\n<< /Size 11 /Root 1 0 R /Prev {prev} {} >>\nstartxref\n{xref}\n%%EOF\n", trailer_extra()).as_bytes());
    v
}

pub fn bases() -> Bases {
    let classic = build_classic(false);
    let incr = build_incremental(&classic);
    Bases {
        classic,
        flate: build_classic(true),
        objstm: build_objstm(),
        incr,
    }
}

// ---- helpers ----

fn find(b: &[u8], pat: &[u8]) -> usize {
    find_from(b, pat, 0)
        .unwrap_or_else(|| panic!("pattern {:?} not in base", String::from_utf8_lossy(pat)))
}

fn find_from(b: &[u8], pat: &[u8], from: usize) -> Option<usize> {
    b[from..]
        .windows(pat.len())
        .position(|w| w == pat)
        .map(|p| p + from)
}

fn rfind(b: &[u8], pat: &[u8]) -> usize {
    b.windows(pat.len())
        .rposition(|w| w == pat)
        .unwrap_or_else(|| panic!("pattern {:?} not in base", String::from_utf8_lossy(pat)))
}

fn replace(b: &[u8], from: &str, to: &str) -> Vec<u8> {
    let p = find(b, from.as_bytes());
    let mut v = b[..p].to_vec();
    v.extend_from_slice(to.as_bytes());
    v.extend_from_slice(&b[p + from.len()..]);
    v
}

fn replace_same_len(b: &[u8], from: &str, to: &str) -> Vec<u8> {
    assert_eq!(from.len(), to.len(), "{from} -> {to}");
    replace(b, from, to)
}

fn last_startxref(b: &[u8]) -> usize {
    let p = rfind(b, b"startxref") + 10;
    let e = p + b[p..].iter().position(|c| !c.is_ascii_digit()).unwrap();
    std::str::from_utf8(&b[p..e]).unwrap().parse().unwrap()
}

/// Byte range of the stream payload of object `num` (first occurrence).
fn stream_range(b: &[u8], num: u32) -> (usize, usize) {
    let o = find(b, format!("\n{num} 0 obj\n").as_bytes());
    let s = find_from(b, b"stream\n", o).unwrap() + 7;
    let e = find_from(b, b"\nendstream", s).unwrap();
    (s, e)
}

/// Offsets of each 20-byte entry of the (last) classic xref table.
fn xref_entries(b: &[u8]) -> Vec<usize> {
    let x = rfind(b, b"\nxref\n") + 6;
    let hdr_end = x + b[x..].iter().position(|&c| c == b'\n').unwrap() + 1;
    let n: usize = std::str::from_utf8(&b[x..hdr_end - 1])
        .unwrap()
        .split(' ')
        .nth(1)
        .unwrap()
        .parse()
        .unwrap();
    (0..n).map(|i| hdr_end + i * 20).collect()
}

fn set_offset(v: &mut [u8], entry: usize, off: usize) {
    v[entry..entry + 10].copy_from_slice(format!("{off:010}").as_bytes());
}

/// Rewrite the first content stream's /Length value, padding with spaces to keep the file length when the new value is not wider.
fn set_len(b: &[u8], new: &str) -> Vec<u8> {
    let (s, e) = stream_range(b, 6);
    let old = (e - s).to_string();
    let pad = old
        .len()
        .checked_sub(new.len())
        .map(|n| " ".repeat(n))
        .unwrap_or_default();
    replace(
        b,
        &format!("/Length {old} "),
        &format!("/Length {new}{pad} "),
    )
}

fn cut_xref_to_end(b: &[u8]) -> Vec<u8> {
    b[..rfind(b, b"\nxref\n") + 1].to_vec()
}

fn junk(seed: u64, n: usize) -> Vec<u8> {
    let mut r = Rng::new(seed);
    let mut v = vec![0u8; n];
    r.fill(&mut v);
    v
}

type Fn1 = fn(&Bases) -> Vec<u8>;

pub fn catalogue() -> Vec<(&'static str, &'static str, Fn1)> {
    vec![
        (
            "mal-xref-offsets-shifted",
            "every in-use xref offset is off by +9 (recovery by scanning)",
            |b| {
                let mut v = b.classic.clone();
                for e in xref_entries(&v).into_iter().skip(1) {
                    let off: usize = std::str::from_utf8(&v[e..e + 10]).unwrap().parse().unwrap();
                    set_offset(&mut v, e, off + 9);
                }
                v
            },
        ),
        (
            "mal-xref-offsets-zero",
            "every in-use xref entry has offset 0",
            |b| {
                let mut v = b.classic.clone();
                for e in xref_entries(&v).into_iter().skip(1) {
                    set_offset(&mut v, e, 0);
                }
                v
            },
        ),
        (
            "mal-xref-single-entry-wrong",
            "the xref entry of the first page points into the middle of another object",
            |b| {
                let mut v = b.classic.clone();
                let e = xref_entries(&v)[3];
                set_offset(&mut v, e, 40);
                v
            },
        ),
        (
            "mal-startxref-beyond-eof",
            "startxref points past the end of the file",
            |b| {
                let n = b.classic.len() + 5000;
                let old = last_startxref(&b.classic);
                replace(
                    &b.classic,
                    &format!("startxref\n{old}\n"),
                    &format!("startxref\n{n}\n"),
                )
            },
        ),
        (
            "mal-startxref-not-xref",
            "startxref points at the middle of an object",
            |b| {
                let old = last_startxref(&b.classic);
                replace(
                    &b.classic,
                    &format!("startxref\n{old}\n"),
                    "startxref\n57\n",
                )
            },
        ),
        (
            "mal-startxref-missing",
            "startxref keyword and offset removed, %%EOF kept",
            |b| {
                let p = rfind(&b.classic, b"startxref");
                let mut v = b.classic[..p].to_vec();
                v.extend_from_slice(b"%%EOF\n");
                v
            },
        ),
        (
            "mal-xref-missing",
            "xref table, trailer and startxref removed entirely",
            |b| {
                let mut v = cut_xref_to_end(&b.classic);
                v.extend_from_slice(b"%%EOF\n");
                v
            },
        ),
        (
            "mal-trailer-missing",
            "xref table present but the trailer dictionary is gone",
            |b| {
                let p = rfind(&b.classic, b"trailer");
                let mut v = b.classic[..p].to_vec();
                v.extend_from_slice(b"startxref\n0\n%%EOF\n");
                v
            },
        ),
        (
            "mal-trailer-no-root",
            "trailer without /Root (catalog must be found by scanning)",
            |b| replace_same_len(&b.classic, "/Root 1 0 R", "/Roof 1 0 R"),
        ),
        (
            "mal-xref-subsection-count-wrong",
            "xref subsection header claims 40 entries instead of 11",
            |b| replace_same_len(&b.classic, "xref\n0 11\n", "xref\n0 40\n"),
        ),
        (
            "mal-xref-short-entries",
            "xref entries are 19 bytes (LF only, missing the trailing space)",
            |b| {
                let x = rfind(&b.classic, b"\nxref\n");
                let t = rfind(&b.classic, b"trailer");
                let mut v = b.classic[..x].to_vec();
                v.extend_from_slice(
                    String::from_utf8_lossy(&b.classic[x..t])
                        .replace(" \n", "\n")
                        .as_bytes(),
                );
                v.extend_from_slice(&b.classic[t..]);
                v
            },
        ),
        (
            "mal-endobj-missing",
            "endobj keyword removed from two page objects",
            |b| {
                let mut v = replace(&b.classic, ">>\nendobj\n4 0 obj", ">>\n4 0 obj");
                v = replace(&v, ">>\nendobj\n5 0 obj", ">>\n5 0 obj");
                v
            },
        ),
        (
            "mal-endstream-missing",
            "endstream keyword removed from the first content stream",
            |b| {
                replace(
                    &b.classic,
                    "\nendstream\nendobj\n7 0 obj",
                    "\nendobj\n7 0 obj",
                )
            },
        ),
        (
            "mal-stream-length-short",
            "/Length of the first content stream is 5",
            |b| set_len(&b.classic, "5"),
        ),
        (
            "mal-stream-length-long",
            "/Length of the first content stream is 99999 (past the end of the object)",
            |b| set_len(&b.classic, "99999"),
        ),
        ("mal-stream-length-negative", "/Length is -5", |b| {
            set_len(&b.classic, "-5")
        }),
        (
            "mal-stream-length-indirect-self",
            "/Length is an indirect reference to the stream object itself",
            |b| {
                let (s, e) = stream_range(&b.classic, 6);
                replace(&b.classic, &format!("/Length {}", e - s), "/Length 6 0 R")
            },
        ),
        (
            "mal-stream-length-missing",
            "/Length removed from the first content stream",
            |b| {
                let (s, e) = stream_range(&b.classic, 6);
                replace(&b.classic, &format!("<< /Length {} >>", e - s), "<< >>")
            },
        ),
        (
            "mal-truncated-header-only",
            "only the first 9 bytes of the file",
            |b| b.classic[..9].to_vec(),
        ),
        (
            "mal-truncated-after-first-object",
            "cut right after object 1",
            |b| b.classic[..find(&b.classic, b"2 0 obj")].to_vec(),
        ),
        (
            "mal-truncated-mid-stream",
            "cut in the middle of the second content stream",
            |b| {
                let (s, e) = stream_range(&b.classic, 7);
                b.classic[..(s + e) / 2].to_vec()
            },
        ),
        ("mal-truncated-half", "first half of the file", |b| {
            b.classic[..b.classic.len() / 2].to_vec()
        }),
        (
            "mal-truncated-no-eof",
            "last 60 bytes removed (trailer tail, startxref and %%EOF lost)",
            |b| b.classic[..b.classic.len() - 60].to_vec(),
        ),
        (
            "mal-garbage-before-header",
            "1,500 random bytes precede %PDF- (all offsets are now shifted)",
            |b| {
                let mut v = junk(11, 1500);
                v.extend_from_slice(&b.classic);
                v
            },
        ),
        (
            "mal-garbage-after-eof",
            "10 KB of random bytes after the final %%EOF",
            |b| {
                let mut v = b.classic.clone();
                v.extend(junk(12, 10_240));
                v
            },
        ),
        (
            "mal-header-missing",
            "the %PDF- header line is removed (offsets shift)",
            |b| b.classic[find(&b.classic, b"%\xe2")..].to_vec(),
        ),
        ("mal-header-bad-version", "header says %PDF-9.9", |b| {
            replace_same_len(&b.classic, "%PDF-1.7", "%PDF-9.9")
        }),
        (
            "mal-pagetree-circular",
            "the Pages node lists itself as a kid",
            |b| {
                replace_same_len(
                    &b.classic,
                    "/Kids [3 0 R 4 0 R 5 0 R]",
                    "/Kids [2 0 R 4 0 R 5 0 R]",
                )
            },
        ),
        (
            "mal-pagetree-count-huge",
            "/Count 99999999 on a three-page tree (length-changing)",
            |b| replace(&b.classic, "/Count 3 >>", "/Count 99999999 >>"),
        ),
        (
            "mal-pagetree-kid-missing-object",
            "a kid references the nonexistent object 77",
            |b| {
                replace_same_len(
                    &b.classic,
                    "/Kids [3 0 R 4 0 R 5 0 R] /Count 3 >>",
                    "/Kids [3 0 R 4 0 R 77 0 R] /Count 3>>",
                )
            },
        ),
        (
            "mal-page-parent-loop",
            "page 3's /Parent is page 4 and page 4's /Parent is page 3",
            |b| {
                let v = replace(
                    &b.classic,
                    "/Type /Page /Parent 2 0 R",
                    "/Type /Page /Parent 4 0 R",
                );
                let p = find(&v, b"4 0 obj");
                let q = find_from(&v, b"/Parent 2 0 R", p).unwrap();
                let mut w = v[..q].to_vec();
                w.extend_from_slice(b"/Parent 3 0 R");
                w.extend_from_slice(&v[q + 13..]);
                w
            },
        ),
        (
            "mal-root-is-a-page",
            "trailer /Root points at a page object",
            |b| replace_same_len(&b.classic, "/Root 1 0 R", "/Root 3 0 R"),
        ),
        (
            "mal-pages-type-missing",
            "the page tree node lacks /Type /Pages",
            |b| replace_same_len(&b.classic, "/Type /Pages", "/Tipo /Pages"),
        ),
        (
            "mal-duplicate-objects",
            "object 3 is defined twice with conflicting content (second wins on scan)",
            |b| {
                let p = rfind(&b.classic, b"\nxref\n") + 1;
                let mut v = b.classic[..p].to_vec();
                v.extend_from_slice(
                    b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] >>\nendobj\n",
                );
                v.extend_from_slice(&b.classic[p..]);
                v
            },
        ),
        (
            "mal-nul-bytes-in-dicts",
            "NUL bytes replace every space inside the page dictionaries",
            |b| {
                let mut v = b.classic.clone();
                for n in 3..=5u32 {
                    let o = find(&v, format!("\n{n} 0 obj\n").as_bytes());
                    let e = find_from(&v, b"endobj", o).unwrap();
                    for c in &mut v[o + 8..e] {
                        if *c == b' ' {
                            *c = 0;
                        }
                    }
                }
                v
            },
        ),
        (
            "mal-deep-nesting-50000",
            "an array nested 50,000 deep in the Info dictionary (length-changing)",
            |b| {
                let deep = format!("{}{}", "[".repeat(50_000), "]".repeat(50_000));
                replace(
                    &b.classic,
                    "/Title (Malformation base)",
                    &format!("/Deep {deep} /Title (Malformation base)"),
                )
            },
        ),
        (
            "mal-huge-integer",
            "/Count is 99999999999999999999999999 (length-changing)",
            |b| replace(&b.classic, "/Count 3", "/Count 99999999999999999999999999"),
        ),
        (
            "mal-name-bad-escape",
            "names with invalid #xx escapes",
            |b| replace_same_len(&b.classic, "/BaseFont /Helvetica", "/BaseFont /Hel#ZZica"),
        ),
        (
            "mal-content-unbalanced-string",
            "content stream with an unterminated literal string and stray operators",
            |b| {
                replace_same_len(
                    &b.classic,
                    "(Page 1 of the malformation",
                    "(Page 1 (((((e malformation",
                )
            },
        ),
        (
            "mal-content-inline-image-garbage",
            "inline image (BI) with no ID/EI terminator and binary junk",
            |b| {
                let mut v = b.classic.clone();
                let (s, e) = stream_range(&v, 8);
                let j = junk(13, e - s - 40);
                v[s..s + 40].copy_from_slice(b"q BI /W 100 /H 100 /BPC 8 /CS /RGB ID  \n");
                v[s + 40..e].copy_from_slice(&j);
                v
            },
        ),
        (
            "mal-flate-corrupt-middle",
            "bytes in the middle of the Flate-compressed content stream are flipped",
            |b| {
                let mut v = b.flate.clone();
                let (s, e) = stream_range(&v, 6);
                for c in &mut v[(s + e) / 2..(s + e) / 2 + 4] {
                    *c ^= 0xA5;
                }
                v
            },
        ),
        (
            "mal-flate-bad-adler",
            "Adler-32 checksum of the content stream is wrong",
            |b| {
                let mut v = b.flate.clone();
                let (_, e) = stream_range(&v, 7);
                v[e - 1] ^= 0xFF;
                v
            },
        ),
        (
            "mal-flate-truncated-stream",
            "Flate data for content stream 3 is truncated (zero-filled tail)",
            |b| {
                let mut v = b.flate.clone();
                let (s, e) = stream_range(&v, 8);
                for c in &mut v[(s + e) / 2..e] {
                    *c = 0;
                }
                v
            },
        ),
        (
            "mal-flate-unknown-filter",
            "stream uses /Filter /FlateDecodeX which no reader knows",
            |b| replace(&b.flate, "/Filter /FlateDecode", "/Filter /FlateDecodX"),
        ),
        (
            "mal-objstm-n-too-large",
            "object stream /N larger than the objects it holds",
            |b| replace_same_len(&b.objstm, "/Type /ObjStm /N 7 ", "/Type /ObjStm /N 9 "),
        ),
        (
            "mal-objstm-first-wrong",
            "object stream /First points past the header",
            |b| {
                let p = find(&b.objstm, b"/First ");
                let digits = b.objstm[p + 7..]
                    .iter()
                    .take_while(|c| c.is_ascii_digit())
                    .count();
                let mut v = b.objstm.clone();
                v[p + 7..p + 7 + digits].fill(b'9');
                v
            },
        ),
        (
            "mal-objstm-data-corrupt",
            "bytes inside the Flate data of the object stream are flipped",
            |b| {
                let mut v = b.objstm.clone();
                let o = find(&v, b"/Type /ObjStm");
                let s = find_from(&v, b"stream\n", o).unwrap() + 7;
                for c in &mut v[s + 6..s + 12] {
                    *c ^= 0x5A;
                }
                v
            },
        ),
        (
            "mal-objstm-type-missing",
            "object stream dictionary without /Type /ObjStm",
            |b| replace_same_len(&b.objstm, "/Type /ObjStm", "/Typo /ObjStm"),
        ),
        ("mal-xrefstm-bad-w", "xref stream /W says [1 4 9]", |b| {
            replace_same_len(&b.objstm, "/W [1 4 2]", "/W [1 4 9]")
        }),
        (
            "mal-xrefstm-size-short",
            "xref stream /Size 03 hides most objects",
            |b| {
                let p = rfind(&b.objstm, b"/Type /XRef /Size ");
                let mut v = b.objstm.clone();
                let w = b.objstm[p + 18..]
                    .iter()
                    .take_while(|c| c.is_ascii_digit())
                    .count();
                assert!(w == 2);
                v[p + 18..p + 20].copy_from_slice(b"03");
                v
            },
        ),
        (
            "mal-xrefstm-data-corrupt",
            "Flate data of the xref stream is corrupted",
            |b| {
                let mut v = b.objstm.clone();
                let o = rfind(&v, b"/Type /XRef");
                let s = find_from(&v, b"stream\n", o).unwrap() + 7;
                for c in &mut v[s + 4..s + 8] {
                    *c ^= 0x77;
                }
                v
            },
        ),
        (
            "mal-xrefstm-startxref-off",
            "startxref of an xref-stream file points 3 bytes into the xref object",
            |b| {
                let old = last_startxref(&b.objstm);
                replace_same_len(
                    &b.objstm,
                    &format!("startxref\n{old}\n"),
                    &format!("startxref\n{}\n", old + 3),
                )
            },
        ),
        (
            "mal-prev-loop",
            "incremental update whose /Prev points at its own xref section",
            |b| {
                let prev = last_startxref(&b.classic);
                let cur = last_startxref(&b.incr);
                replace(&b.incr, &format!("/Prev {prev}"), &format!("/Prev {cur}"))
            },
        ),
        (
            "mal-prev-bad-offset",
            "incremental update whose /Prev points into the middle of an object",
            |b| {
                let prev = last_startxref(&b.classic);
                replace(&b.incr, &format!("/Prev {prev}"), "/Prev 30")
            },
        ),
        (
            "mal-incremental-update-ok-baseline",
            "valid incremental update (control: should open cleanly)",
            |b| b.incr.clone(),
        ),
        (
            "mal-linearization-lies",
            "first object claims to be a linearization dictionary with wrong /L /H /O",
            |b| {
                let p = find(&b.classic, b"1 0 obj");
                let mut v = b.classic[..p].to_vec();
                v.extend_from_slice(b"11 0 obj\n<< /Linearized 1 /L 123456 /H [100 200] /O 3 /E 500 /N 3 /T 700 >>\nendobj\n");
                v.extend_from_slice(&b.classic[p..]);
                v
            },
        ),
        (
            "mal-encrypt-dict-bogus",
            "trailer has /Encrypt with an incomplete Standard handler (no /O /U)",
            |b| {
                let v = replace(&b.classic, "/Root 1 0 R", "/Root 1 0 R /Encrypt 11 0 R");
                let p = rfind(&v, b"\nxref\n") + 1;
                let mut w = v[..p].to_vec();
                w.extend_from_slice(
                    b"11 0 obj\n<< /Filter /Standard /V 2 /R 3 /Length 128 /P -4 >>\nendobj\n",
                );
                w.extend_from_slice(&v[p..]);
                w
            },
        ),
        (
            "mal-flate-bomb-1gib",
            "a 1 GiB all-zero Flate content stream stored in about 1 MB (decompression bomb)",
            |_| {
                let zz = bomb_zlib(1024);
                let mut o = Out::new(Vec::new());
                o.header("1.7").unwrap();
                o.obj(1, b"<< /Type /Catalog /Pages 2 0 R >>").unwrap();
                o.obj(2, b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
                    .unwrap();
                o.obj(
                    3,
                    b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> /Contents 4 0 R >>",
                )
                .unwrap();
                o.stream(4, "/Filter /FlateDecode", &zz).unwrap();
                o.finish_classic(1, "").unwrap();
                o.into_inner()
            },
        ),
    ]
}

/// zlib stream that inflates to `mib` MiB of 0x20 bytes.
fn bomb_zlib(mib: usize) -> Vec<u8> {
    use miniz_oxide::deflate::core::{
        CompressorOxide, TDEFLFlush, TDEFLStatus, compress, create_comp_flags_from_zip_params,
    };
    let chunk = vec![b' '; 1 << 20];
    let mut z = CompressorOxide::new(create_comp_flags_from_zip_params(9, 0, 0));
    let mut out = vec![0x78, 0xDA];
    let mut buf = vec![0u8; 1 << 16];
    for i in 0..mib {
        let flush = if i + 1 == mib {
            TDEFLFlush::Finish
        } else {
            TDEFLFlush::None
        };
        let mut inp: &[u8] = &chunk;
        loop {
            let (status, used, wrote) = compress(&mut z, inp, &mut buf, flush);
            out.extend_from_slice(&buf[..wrote]);
            inp = &inp[used..];
            if status == TDEFLStatus::Done || (inp.is_empty() && flush == TDEFLFlush::None) {
                break;
            }
        }
    }
    let n = chunk.len() as u64;
    let (mut a, mut b) = (1u64, 0u64);
    for _ in 0..mib {
        b = (b + a * n + 32 * n * (n + 1) / 2) % 65521;
        a = (a + 32 * n) % 65521;
    }
    out.extend_from_slice(&(((b << 16) | a) as u32).to_be_bytes());
    out
}
