#!/usr/bin/env python3
"""Extract expectEventValue(...) cases for the AF *Format* functions from PDFium's
testing/resources/javascript/public_methods.in (BSD-3-Clause, (c) The PDFium Authors)
into crates/papyrine-forms/tests/data/pdfium_format_cases.in.

usage: gen_pdfium_cases.py PATH/TO/public_methods.in
Fetch the source with:
  curl -s 'https://pdfium.googlesource.com/pdfium/+archive/refs/heads/main/testing/resources/javascript.tar.gz' | tar xz public_methods.in
"""
import re, sys

src = open(sys.argv[1], encoding="utf-8").read().split("\n")
pat = re.compile(r"""^\s*expectEventValue\((.+?),\s*"((?:AFPercent_Format|AFNumber_Format|AFSpecial_Format|AFDate_FormatEx|AFSimple_Calculate)\(.*)",\s*(.+?)\);""")

def lit(s):
    s = s.strip()
    if len(s) >= 2 and s[0] in "'\"" and s[-1] == s[0]:
        return s[1:-1]
    return s  # numeric literal: JS ToString of these literals is the literal itself

rows = []
for i, line in enumerate(src, 1):
    m = pat.match(line)
    if not m: continue
    init, expr, exp = m.groups()
    if re.search(r"[+*/]", exp) and not exp.strip().startswith(("'", '"')):  # e.g. (123 + 456) / 2
        v = eval(exp)
        exp = repr(round(v, 6))
        if exp.endswith(".0"): exp = exp[:-2]
    rows.append((i, lit(init), expr, lit(exp)))

with open(sys.argv[2], "w") as f:
    f.write("// Generated by spikes/forms/gen_pdfium_cases.py from PDFium\n")
    f.write("// testing/resources/javascript/public_methods.in (BSD-3-Clause, The PDFium Authors).\n")
    f.write("// (source line, initial event.value, expression, expected event.value)\n")
    f.write("&[\n")
    for ln, i, e, x in rows:
        f.write('    (%d, r#"%s"#, r#"%s"#, r#"%s"#),\n' % (ln, i, e, x))
    f.write("]\n")
print(len(rows), "cases")
