#!/usr/bin/env python3
"""Write corpus/js-forms.toml (schema in corpus/README.md) for the JS forms found by Spike 0.4.

usage: make_manifest.py SCRIPTS.jsonl FETCH_META.json OUT.toml [--pin-pdfjs]
Only forms with at least one non-empty script are listed. With --pin-pdfjs the pdf.js URLs are
rewritten to the current mozilla/pdf.js commit and the hash re-verified against a fresh download.
"""
import collections, hashlib, json, subprocess, sys

scripts_path, meta_path, out_path = sys.argv[1:4]
meta = json.load(open(meta_path))
forms = collections.OrderedDict()
for l in open(scripts_path):
    d = json.loads(l)
    f = forms.setdefault(d["form"], {"js": False, "meta": {}})
    if "meta" in d: f["meta"] = d["meta"]
    if d.get("script", "").strip(): f["js"] = True

REGION = {"irs": "us-federal", "opm": "us-federal", "uscis": "us-federal", "state-dept": "us-federal", "cms": "us-federal",
          "uscourts": "us-federal", "dol": "us-federal", "usps": "us-federal", "fda": "us-federal",
          "ca": "us-state", "ny": "us-state", "fl": "us-state", "tx": "us-state", "il": "us-state", "or": "us-state", "ok": "us-state",
          "gov-uk": "uk", "ircc": "canada", "cra": "canada", "homeaffairs": "australia", "ato": "australia", "pdfjs-corpus": "pdfjs"}

commit = None
if "--pin-pdfjs" in sys.argv:
    commit = subprocess.check_output(["gh", "api", "repos/mozilla/pdf.js/commits/HEAD", "-q", ".sha"], text=True).strip()

def lic_short(s):
    return s if len(s) < 80 else s[:77] + "..."

lines = ["# Form-script corpus (Spike 0.4): public PDF forms that contain JavaScript.",
         "# Schema: corpus/README.md. Generated by spikes/forms/make_manifest.py.",
         "#",
         "# Government form URLs are \"latest\" links and cannot be pinned, so a hash mismatch after an",
         "# agency republishes a form is expected; regenerate with spikes/forms/make_manifest.py.",
         "# Files are fetched for testing only and never redistributed (ADR-017).",
         ""]
n = 0
dropped = 0
for fid, f in forms.items():
    if not f["js"] or fid not in meta: continue
    m = meta[fid]
    url, sha = m["url"], m["sha256"]
    if commit and m["source"] == "pdfjs-corpus":
        url = url.replace("/HEAD/", "/%s/" % commit)
        data = subprocess.run(["curl", "-sSL", "-f", "--max-time", "60", url], capture_output=True).stdout
        if hashlib.sha256(data).hexdigest() != sha:
            dropped += 1; continue
    tags = ["js-form", m["source"], REGION.get(m["source"], "other"), "js"]
    if f["meta"].get("acroform"): tags.append("forms")
    if f["meta"].get("xfa"): tags.append("xfa")
    if f["meta"].get("encrypted"): tags.append("encrypted")
    if m["size"] > 1_000_000: tags.append("large")
    src = m["source"] if m["source"] != "pdfjs-corpus" else "mozilla/pdf.js@%s" % (commit or "HEAD")
    lines += ["[[file]]", 'id      = "js-forms/%s.pdf"' % fid, 'url     = "%s"' % url, 'sha256  = "%s"' % sha,
              'license = "%s"' % lic_short(m["license"]).replace('"', "'"), 'source  = "%s"' % src,
              "tags    = [%s]" % ", ".join('"%s"' % t for t in tags), "size    = %d" % m["size"], ""]
    n += 1
open(out_path, "w").write("\n".join(lines))
print(n, "entries", "(dropped %d unpinnable)" % dropped if dropped else "")
