//! 30 curated corpus files whose expected values come from `qpdf --json=2` (generated by
//! tests/tools/gen_curated.py into tests/curated.toml, independently of this crate).
//! Skipped when `corpus/cache` is absent.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use papyrine_core::geom::Rect;
use papyrine_cos::OpenOptions;
use papyrine_model::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct Curated {
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    id: String,
    password: Option<String>,
    pages: usize,
    header_version: String,
    has_outlines: bool,
    has_page_labels: bool,
    has_acroform: bool,
    has_embedded_files: bool,
    has_xmp: bool,
    is_marked: bool,
    lang: Option<String>,
    catalog_version: Option<String>,
    doc_scripts: usize,
    signed_fields: usize,
    info: Option<BTreeMap<String, String>>,
    outline: Option<OutlineExp>,
    form: Option<FormExp>,
    encrypt: Option<EncExp>,
    page: Vec<PageExp>,
}

#[derive(Deserialize)]
struct OutlineExp {
    total: usize,
    top: usize,
    titles: Vec<String>,
}

#[derive(Deserialize)]
struct FormExp {
    widgets: usize,
    fields: usize,
    need_appearances: bool,
    has_xfa: bool,
    sig_flags: u32,
    types: BTreeMap<String, usize>,
    #[serde(default)]
    first: Vec<FirstField>,
}

#[derive(Deserialize)]
struct FirstField {
    name: String,
    flags: i32,
    value: Option<String>,
    page: Option<usize>,
}

#[derive(Deserialize)]
struct EncExp {
    r: u8,
    v: u8,
    method: String,
    p: i32,
    accessibility: bool,
    extract: bool,
    modifyannotations: bool,
    modifyassembly: bool,
    modifyforms: bool,
    modifyother: bool,
    printhigh: bool,
    printlow: bool,
}

#[derive(Deserialize)]
struct PageExp {
    index: usize,
    media: Option<[f64; 4]>,
    crop: Option<[f64; 4]>,
    rotate: u16,
    label: String,
    annots: BTreeMap<String, usize>,
}

fn cache() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus/cache")
}

fn rect_eq(a: Rect, b: [f64; 4]) -> bool {
    let e = 1e-3; // qpdf's JSON trims reals to 6 significant digits
    (a.x0 - b[0]).abs() < e
        && (a.y0 - b[1]).abs() < e
        && (a.x1 - b[2]).abs() < e
        && (a.y1 - b[3]).abs() < e
}

fn kind_name(k: &FieldKind) -> &'static str {
    match k {
        FieldKind::Text => "Text",
        FieldKind::PushButton => "PushButton",
        FieldKind::Checkbox => "Checkbox",
        FieldKind::Radio => "Radio",
        FieldKind::ComboBox => "Combo",
        FieldKind::ListBox => "List",
        FieldKind::Signature => "Signature",
        FieldKind::Unknown => "?",
    }
}

fn check(c: &Case, fails: &mut Vec<String>) {
    let mut bad = |what: &str, got: String, want: String| {
        if got != want {
            fails.push(format!("{}: {what}: model {got} != qpdf {want}", c.id));
        }
    };
    let opts = match &c.password {
        Some(p) => OpenOptions::with_password(p.as_str()),
        None => OpenOptions::default(),
    };
    let m = match Model::open_path(cache().join(&c.id), &opts) {
        Ok(m) => m,
        Err(e) => {
            bad("open", format!("{e}"), "ok".into());
            return;
        }
    };
    let b = |v: bool| v.to_string();
    bad(
        "pages",
        format!("{:?}", m.page_count().ok()),
        format!("{:?}", Some(c.pages)),
    );

    let cat = m.catalog_info().unwrap();
    bad(
        "header_version",
        cat.header_version.clone(),
        c.header_version.clone(),
    );
    bad("has_outlines", b(cat.has_outlines), b(c.has_outlines));
    bad(
        "has_page_labels",
        b(cat.has_page_labels),
        b(c.has_page_labels),
    );
    bad("has_acroform", b(cat.has_acroform), b(c.has_acroform));
    bad(
        "has_embedded_files",
        b(cat.has_embedded_files),
        b(c.has_embedded_files),
    );
    bad("has_xmp", b(cat.has_xmp), b(c.has_xmp));
    bad("is_marked", b(cat.is_marked), b(c.is_marked));
    bad(
        "lang",
        format!("{:?}", cat.language),
        format!("{:?}", c.lang),
    );
    bad(
        "catalog_version",
        format!("{:?}", cat.catalog_version),
        format!("{:?}", c.catalog_version),
    );
    bad(
        "doc_scripts",
        m.scripts().unwrap().document_level().count().to_string(),
        c.doc_scripts.to_string(),
    );
    bad(
        "signed_fields",
        m.signatures().unwrap().signed_count().to_string(),
        c.signed_fields.to_string(),
    );

    if let Some(info) = &c.info {
        let i = m.info().unwrap();
        for (k, want) in info {
            let got = match k.as_str() {
                "title" => &i.title,
                "author" => &i.author,
                "subject" => &i.subject,
                "creator" => &i.creator,
                "producer" => &i.producer,
                "creation_date_raw" => &i.creation_date_raw,
                _ => continue,
            };
            bad(
                &format!("info.{k}"),
                format!("{got:?}"),
                format!("{:?}", Some(want)),
            );
        }
    }

    match &c.outline {
        Some(exp) => {
            let o = m.outlines().unwrap();
            bad(
                "outline.total",
                o.total().to_string(),
                exp.total.to_string(),
            );
            bad(
                "outline.top",
                o.items.len().to_string(),
                exp.top.to_string(),
            );
            let titles: Vec<&str> = o.items.iter().take(3).map(|i| i.title.as_str()).collect();
            bad(
                "outline.titles",
                format!("{titles:?}"),
                format!("{:?}", exp.titles),
            );
        }
        None => bad(
            "outline.total",
            m.outlines().unwrap().total().to_string(),
            "0".into(),
        ),
    }

    if let Some(exp) = &c.form {
        let f = m.form().unwrap();
        bad(
            "form.widgets",
            f.widget_count().to_string(),
            exp.widgets.to_string(),
        );
        // qpdf lists one entry per (field, widget); `fields` is the number of distinct full names.
        let names: std::collections::BTreeSet<&str> = f
            .terminal_fields()
            .filter(|x| !x.widgets.is_empty())
            .map(|x| x.qualified_name.as_str())
            .collect();
        bad(
            "form.fields",
            names.len().to_string(),
            exp.fields.to_string(),
        );
        bad(
            "form.need_appearances",
            b(f.need_appearances),
            b(exp.need_appearances),
        );
        bad("form.has_xfa", b(f.xfa != XfaKind::None), b(exp.has_xfa));
        bad(
            "form.sig_flags",
            f.sig_flags.to_string(),
            exp.sig_flags.to_string(),
        );
        let mut types: BTreeMap<String, usize> = BTreeMap::new();
        for fld in f.terminal_fields() {
            if !fld.widgets.is_empty() {
                *types.entry(kind_name(&fld.kind).to_string()).or_default() += fld.widgets.len();
            }
        }
        bad(
            "form.types",
            format!("{types:?}"),
            format!("{:?}", exp.types),
        );
        for want in &exp.first {
            let Some(fld) = f.find(&want.name) else {
                bad("form.first", "missing".into(), want.name.clone());
                continue;
            };
            let n = &want.name;
            bad(
                &format!("form[{n}].flags"),
                (fld.flags as i32).to_string(),
                want.flags.to_string(),
            );
            if let Some(v) = &want.value {
                let got = match &fld.value {
                    FieldValue::Name(n) => format!("/{n}"),
                    FieldValue::Text(t) => t.clone(),
                    other => format!("{other:?}"),
                };
                bad(&format!("form[{n}].value"), got, v.clone());
            }
            if let Some(p) = want.page {
                let got = fld.widgets.first().and_then(|w| w.page);
                bad(
                    &format!("form[{n}].page"),
                    format!("{got:?}"),
                    format!("{:?}", Some(p)),
                );
            }
        }
    } else {
        bad(
            "form.fields",
            m.form().unwrap().terminal_fields().count().to_string(),
            "0".into(),
        );
    }

    match &c.encrypt {
        Some(e) => {
            let s = m.security().unwrap();
            let info = s.info.as_ref();
            bad("encrypt.encrypted", b(s.encrypted), "true".into());
            let info = info.unwrap();
            bad("encrypt.r", info.revision.to_string(), e.r.to_string());
            bad("encrypt.v", info.version.to_string(), e.v.to_string());
            bad(
                "encrypt.method",
                format!("{:?}", info.stream_method),
                match e.method.as_str() {
                    "RC4" => "Rc4".into(),
                    "AESv2" => "Aes128".into(),
                    "AESv3" => "Aes256".into(),
                    o => o.to_string(),
                },
            );
            bad("encrypt.p", info.permissions.to_string(), e.p.to_string());
            // qpdf's capabilities ignore the owner password, so compare with what /P declares.
            let d = s.declared;
            for (name, got, want) in [
                ("accessibility", d.accessibility, e.accessibility),
                ("extract", d.copy, e.extract),
                ("modifyannotations", d.annotate, e.modifyannotations),
                ("modifyassembly", d.assemble, e.modifyassembly),
                ("modifyforms", d.fill_forms, e.modifyforms),
                ("modifyother", d.modify_contents, e.modifyother),
                ("printhigh", d.print_high_quality, e.printhigh),
                ("printlow", d.print, e.printlow),
            ] {
                bad(&format!("encrypt.{name}"), b(got), b(want));
            }
        }
        None => bad(
            "encrypt.encrypted",
            b(m.security().unwrap().encrypted),
            "false".into(),
        ),
    }

    let labels = m.page_labels().unwrap();
    for p in &c.page {
        let page = match m.page(p.index) {
            Ok(p) => p,
            Err(e) => {
                bad(&format!("page[{}]", p.index), format!("{e}"), "ok".into());
                continue;
            }
        };
        if let (Some(media), Some(crop)) = (p.media, p.crop) {
            if !rect_eq(page.boxes.media, media) {
                bad(
                    &format!("page[{}].media", p.index),
                    format!("{:?}", page.boxes.media),
                    format!("{media:?}"),
                );
            }
            if !rect_eq(page.boxes.crop, crop) {
                bad(
                    &format!("page[{}].crop", p.index),
                    format!("{:?}", page.boxes.crop),
                    format!("{crop:?}"),
                );
            }
        }
        bad(
            &format!("page[{}].rotate", p.index),
            page.rotate.to_string(),
            p.rotate.to_string(),
        );
        bad(
            &format!("page[{}].label", p.index),
            labels.label(p.index),
            p.label.clone(),
        );
        let mut hist: BTreeMap<String, usize> = BTreeMap::new();
        for a in &m.annotations(p.index).unwrap().items {
            *hist.entry(a.subtype.name().to_string()).or_default() += 1;
        }
        bad(
            &format!("page[{}].annots", p.index),
            format!("{hist:?}"),
            format!("{:?}", p.annots),
        );
    }
}

#[test]
fn thirty_curated_files_match_qpdf() {
    if !cache().exists() {
        eprintln!("corpus/cache absent: skipping");
        return;
    }
    let text =
        std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/curated.toml"))
            .unwrap();
    let cur: Curated = toml::from_str(&text).unwrap();
    assert_eq!(cur.case.len(), 30, "the curated set is 30 files");
    let mut fails = Vec::new();
    let mut ran = 0;
    for c in &cur.case {
        if !cache().join(&c.id).exists() {
            eprintln!("missing {}: skipped", c.id);
            continue;
        }
        check(c, &mut fails);
        ran += 1;
    }
    eprintln!("curated: {ran} files checked, {} mismatches", fails.len());
    assert!(
        fails.is_empty(),
        "{} mismatches:\n{}",
        fails.len(),
        fails.join("\n")
    );
}
